// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnpopzuzyunywxqvvntu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZucG9wenV6eXVueXd4cXZ2bnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDEyMjMsImV4cCI6MjA2NDUxNzIyM30.ukFPdKAIrYMZ3ZyAzZQr1egeo9QotE_kdmRXhxj47hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);